"""baseline

Revision ID: 0000
Revises:
Create Date: 2026-03-31 15:57:07.604544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auth0_org_id', sa.String(), nullable=True),
    sa.Column('org_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_organization_auth0_org_id', 'organization', ['auth0_org_id'], unique=False)
    op.create_table('processed_webhook_event',
    sa.Column('stripe_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_webhook_event_stripe_event_id'), 'processed_webhook_event', ['stripe_event_id'], unique=True)
    op.create_table('user',
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('auth0_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('auth0_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vector_db_deployment_metadata',
    sa.Column('singleton', sa.Boolean(), nullable=False),
    sa.Column('dense_embedder', sa.String(), nullable=False),
    sa.Column('embedding_dimensions', sa.Integer(), nullable=False),
    sa.Column('sparse_embedder', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('singleton'),
    comment='Singleton table — exactly one row, enforced by CHECK(singleton)'
    )
    op.create_table('api_key',
    sa.Column('encrypted_key', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encrypted_key')
    )
    op.create_index(op.f('ix_api_key_organization_id'), 'api_key', ['organization_id'], unique=False)
    op.create_table('auth_provider',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('auth_config_class', sa.String(), nullable=False),
    sa.Column('config_class', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='uq_auth_provider_name_org'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('billing_period',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_from', sa.String(length=50), nullable=False),
    sa.Column('previous_period_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('period_end > period_start', name='check_period_end_after_start'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_period_id'], ['billing_period.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_billing_period_org_dates', 'billing_period', ['organization_id', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_billing_period_org_status', 'billing_period', ['organization_id', 'status'], unique=False)
    op.create_table('collection',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('readable_id', sa.String(), nullable=False),
    sa.Column('vector_db_deployment_metadata_id', sa.UUID(), nullable=False),
    sa.Column('sync_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vector_db_deployment_metadata_id'], ['vector_db_deployment_metadata.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('readable_id')
    )
    op.create_index('idx_collection_vdb_metadata_id', 'collection', ['vector_db_deployment_metadata_id'], unique=False)
    op.create_index(op.f('ix_collection_organization_id'), 'collection', ['organization_id'], unique=False)
    op.create_table('entity_definition',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('FILE', 'JSON', name='entitytype'), nullable=False),
    sa.Column('entity_schema', sa.JSON(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('module_name', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['entity_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'organization_id', name='uq_entity_definition_name_org')
    )
    op.create_table('entity_relation',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('from_entity_definition_short_name', sa.String(), nullable=False),
    sa.Column('to_entity_definition_short_name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_entity_definition_short_name', 'to_entity_definition_short_name', 'name', 'organization_id', name='uq_entity_relation')
    )
    op.create_index('idx_entity_relation_from', 'entity_relation', ['from_entity_definition_short_name'], unique=False)
    op.create_index('idx_entity_relation_to', 'entity_relation', ['to_entity_definition_short_name'], unique=False)
    op.create_table('feature_flag',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('flag', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'flag', name='uq_org_flag')
    )
    op.create_index(op.f('ix_feature_flag_organization_id'), 'feature_flag', ['organization_id'], unique=False)
    op.create_table('integration_credential',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('integration_short_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('authentication_method', sa.String(), nullable=False),
    sa.Column('oauth_type', sa.String(), nullable=True),
    sa.Column('encrypted_credentials', sa.Text(), nullable=False),
    sa.Column('auth_config_class', sa.String(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_credential_organization_id'), 'integration_credential', ['organization_id'], unique=False)
    op.create_table('organization_billing',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('billing_plan', sa.String(length=50), nullable=False),
    sa.Column('billing_status', sa.String(length=50), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('grace_period_ends_at', sa.DateTime(), nullable=True),
    sa.Column('payment_method_added', sa.Boolean(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('pending_plan_change', sa.String(length=50), nullable=True),
    sa.Column('pending_plan_change_at', sa.DateTime(), nullable=True),
    sa.Column('billing_email', sa.String(), nullable=False),
    sa.Column('payment_method_id', sa.String(), nullable=True),
    sa.Column('last_payment_status', sa.String(length=50), nullable=True),
    sa.Column('last_payment_at', sa.DateTime(), nullable=True),
    sa.Column('billing_metadata', sa.JSON(), nullable=True),
    sa.Column('has_yearly_prepay', sa.Boolean(), nullable=False),
    sa.Column('yearly_prepay_started_at', sa.DateTime(), nullable=True),
    sa.Column('yearly_prepay_expires_at', sa.DateTime(), nullable=True),
    sa.Column('yearly_prepay_amount_cents', sa.Integer(), nullable=True),
    sa.Column('yearly_prepay_coupon_id', sa.String(), nullable=True),
    sa.Column('yearly_prepay_payment_intent_id', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_table('redirect_session',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('final_url', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_redirect_session_expires_at', 'redirect_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_redirect_session_code'), 'redirect_session', ['code'], unique=True)
    op.create_index(op.f('ix_redirect_session_organization_id'), 'redirect_session', ['organization_id'], unique=False)
    op.create_table('source_rate_limits',
    sa.Column('source_short_name', sa.String(length=100), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'source_short_name', name='uq_org_source_rate_limit')
    )
    op.create_index(op.f('ix_source_rate_limits_organization_id'), 'source_rate_limits', ['organization_id'], unique=False)
    op.create_table('sync',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'INACTIVE', 'ERROR', name='syncstatus'), nullable=False),
    sa.Column('cron_schedule', sa.String(length=100), nullable=True),
    sa.Column('next_scheduled_run', sa.DateTime(), nullable=True),
    sa.Column('temporal_schedule_id', sa.String(length=255), nullable=True),
    sa.Column('sync_type', sa.String(length=50), nullable=False),
    sa.Column('sync_metadata', sa.JSON(), nullable=True),
    sa.Column('sync_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_organization_id'), 'sync', ['organization_id'], unique=False)
    op.create_table('user_organization',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization')
    )
    op.create_table('connection',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('readable_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('integration_type', sa.Enum('SOURCE', 'DESTINATION', 'AUTH_PROVIDER', name='integrationtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ERROR', name='connectionstatus'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.Column('integration_credential_id', sa.UUID(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("\n            (short_name IN ('qdrant_native', 'neo4j_native', 'vespa_native', 'local_text2vec'))\n            OR\n            (organization_id IS NOT NULL)\n            ", name='ck_connection_native_or_complete'),
    sa.ForeignKeyConstraint(['integration_credential_id'], ['integration_credential.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('readable_id')
    )
    op.create_index('idx_connection_integration_credential_id', 'connection', ['integration_credential_id'], unique=False)
    op.create_index('idx_connection_organization_id', 'connection', ['organization_id'], unique=False)
    op.create_table('entity_count',
    sa.Column('sync_id', sa.UUID(), nullable=False),
    sa.Column('entity_definition_short_name', sa.String(), nullable=False, comment='Registry short_name (e.g. asana_task_entity)'),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('modified_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['sync_id'], ['sync.id'], name='fk_entity_count_sync_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_id', 'entity_definition_short_name', name='uq_sync_entity_def_short_name')
    )
    op.create_index('idx_entity_count_entity_def_short_name', 'entity_count', ['entity_definition_short_name'], unique=False)
    op.create_index('idx_entity_count_sync_id', 'entity_count', ['sync_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('collection_id', sa.UUID(), nullable=False, comment='Collection that was searched'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed the search (null for API key searches)'),
    sa.Column('api_key_id', sa.UUID(), nullable=True, comment='API key used for the search (null for user searches)'),
    sa.Column('query_text', sa.Text(), nullable=False, comment='The actual search query text'),
    sa.Column('query_length', sa.Integer(), nullable=False, comment='Length of the search query in characters'),
    sa.Column('is_streaming', sa.Boolean(), server_default='false', nullable=False, comment='Whether this was a streaming search'),
    sa.Column('retrieval_strategy', sa.String(length=20), nullable=False, comment="Retrieval strategy: 'hybrid', 'neural', 'keyword'"),
    sa.Column('limit', sa.Integer(), nullable=False, comment='Maximum number of results requested'),
    sa.Column('offset', sa.Integer(), nullable=False, comment='Number of results to skip for pagination'),
    sa.Column('temporal_relevance', sa.Float(), nullable=False, comment='Temporal relevance weight (0.0 to 1.0)'),
    sa.Column('filter', sa.JSON(), nullable=True, comment='Qdrant filter applied (if any)'),
    sa.Column('duration_ms', sa.Integer(), nullable=False, comment='Search execution time in milliseconds'),
    sa.Column('results_count', sa.Integer(), nullable=False, comment='Number of results returned'),
    sa.Column('expand_query', sa.Boolean(), nullable=False, comment='Whether query expansion was enabled'),
    sa.Column('interpret_filters', sa.Boolean(), nullable=False, comment='Whether query interpretation was enabled'),
    sa.Column('rerank', sa.Boolean(), nullable=False, comment='Whether LLM reranking was enabled'),
    sa.Column('generate_answer', sa.Boolean(), nullable=False, comment='Whether answer generation was enabled'),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_key.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_queries_api_key_created', 'search_queries', ['api_key_id', 'created_at'], unique=False)
    op.create_index('ix_search_queries_collection_created', 'search_queries', ['collection_id', 'created_at'], unique=False)
    op.create_index('ix_search_queries_duration', 'search_queries', ['duration_ms'], unique=False)
    op.create_index('ix_search_queries_is_streaming', 'search_queries', ['is_streaming'], unique=False)
    op.create_index('ix_search_queries_org_created', 'search_queries', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_queries_organization_id'), 'search_queries', ['organization_id'], unique=False)
    op.create_index('ix_search_queries_results_count', 'search_queries', ['results_count'], unique=False)
    op.create_index('ix_search_queries_retrieval_strategy', 'search_queries', ['retrieval_strategy'], unique=False)
    op.create_index('ix_search_queries_user_created', 'search_queries', ['user_id', 'created_at'], unique=False)
    op.create_table('sync_cursor',
    sa.Column('sync_id', sa.UUID(), nullable=True),
    sa.Column('cursor_data', sa.JSON(), nullable=False),
    sa.Column('cursor_field', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['sync.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_id')
    )
    op.create_index(op.f('ix_sync_cursor_organization_id'), 'sync_cursor', ['organization_id'], unique=False)
    op.create_table('sync_job',
    sa.Column('sync_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('entities_inserted', sa.Integer(), nullable=False),
    sa.Column('entities_updated', sa.Integer(), nullable=False),
    sa.Column('entities_deleted', sa.Integer(), nullable=False),
    sa.Column('entities_kept', sa.Integer(), nullable=False),
    sa.Column('entities_skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('error_category', sa.String(length=64), nullable=True),
    sa.Column('entities_encountered', sa.JSON(), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=False),
    sa.Column('sync_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sync_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['sync.id'], name='fk_sync_job_sync_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sync_job_status', 'sync_job', ['status'], unique=False)
    op.create_index('idx_sync_job_status_modified_at', 'sync_job', ['status', 'modified_at'], unique=False)
    op.create_index('idx_sync_job_status_started_at', 'sync_job', ['status', 'started_at'], unique=False)
    op.create_index('idx_sync_job_sync_id', 'sync_job', ['sync_id'], unique=False)
    op.create_index(op.f('ix_sync_job_organization_id'), 'sync_job', ['organization_id'], unique=False)
    op.create_table('usage',
    sa.Column('billing_period_id', sa.UUID(), nullable=True),
    sa.Column('entities', sa.Integer(), server_default='0', nullable=False),
    sa.Column('queries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_period_id'], ['billing_period.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_period_id')
    )
    op.create_index('ix_usage_billing_period_id', 'usage', ['billing_period_id'], unique=False)
    op.create_index(op.f('ix_usage_organization_id'), 'usage', ['organization_id'], unique=False)
    op.create_table('connection_init_session',
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('overrides', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initiator_user_id', sa.UUID(), nullable=True),
    sa.Column('initiator_session_id', sa.Uuid(), nullable=True),
    sa.Column('claim_token_hash', sa.String(length=64), nullable=True),
    sa.Column('final_connection_id', sa.UUID(), nullable=True),
    sa.Column('redirect_session_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['final_connection_id'], ['connection.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['redirect_session_id'], ['redirect_session.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connection_init_session_expires_at', 'connection_init_session', ['expires_at'], unique=False)
    op.create_index(op.f('ix_connection_init_session_organization_id'), 'connection_init_session', ['organization_id'], unique=False)
    op.create_index(op.f('ix_connection_init_session_state'), 'connection_init_session', ['state'], unique=True)
    op.create_table('entity',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sync_job_id', sa.UUID(), nullable=False),
    sa.Column('sync_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('entity_definition_short_name', sa.String(), nullable=True, comment='Entity definition short_name from the registry (e.g. asana_task_entity)'),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['sync.id'], name='fk_entity_sync_id', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_job_id'], ['sync_job.id'], name='fk_entity_sync_job_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_id', 'entity_id', 'entity_definition_short_name', name='uq_sync_id_entity_id_entity_def_short_name')
    )
    op.create_index('idx_entity_entity_def_short_name', 'entity', ['entity_definition_short_name'], unique=False)
    op.create_index('idx_entity_entity_id', 'entity', ['entity_id'], unique=False)
    op.create_index('idx_entity_entity_id_sync_id', 'entity', ['entity_id', 'sync_id'], unique=False)
    op.create_index('idx_entity_sync_id', 'entity', ['sync_id'], unique=False)
    op.create_index('idx_entity_sync_id_entity_def_short_name', 'entity', ['sync_id', 'entity_definition_short_name'], unique=False)
    op.create_index('idx_entity_sync_job_id', 'entity', ['sync_job_id'], unique=False)
    op.create_table('sync_connection',
    sa.Column('sync_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['sync.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_id', 'connection_id', name='uq_sync_connection')
    )
    op.create_index('idx_sync_connection_connection_id', 'sync_connection', ['connection_id'], unique=False)
    op.create_index('idx_sync_connection_sync_id', 'sync_connection', ['sync_id'], unique=False)
    op.create_table('source_connection',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('config_fields', sa.JSON(), nullable=True),
    sa.Column('readable_auth_provider_id', sa.String(), nullable=True),
    sa.Column('auth_provider_config', sa.JSON(), nullable=True),
    sa.Column('sync_id', sa.UUID(), nullable=True),
    sa.Column('readable_collection_id', sa.String(), nullable=True),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('connection_init_session_id', sa.UUID(), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_email', sa.String(), nullable=True),
    sa.Column('modified_by_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['connection.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['connection_init_session_id'], ['connection_init_session.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['readable_auth_provider_id'], ['connection.readable_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['readable_collection_id'], ['collection.readable_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sync_id'], ['sync.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_connection_collection_id', 'source_connection', ['readable_collection_id'], unique=False)
    op.create_index('idx_source_connection_connection_id', 'source_connection', ['connection_id'], unique=False)
    op.create_index('idx_source_connection_sync_id', 'source_connection', ['sync_id'], unique=False)
    op.create_index(op.f('ix_source_connection_organization_id'), 'source_connection', ['organization_id'], unique=False)
    op.create_table('access_control_membership',
    sa.Column('member_id', sa.String(length=255), nullable=False),
    sa.Column('member_type', sa.String(length=10), nullable=False),
    sa.Column('group_id', sa.String(length=255), nullable=False),
    sa.Column('group_name', sa.String(length=255), nullable=True),
    sa.Column('source_name', sa.String(length=50), nullable=False),
    sa.Column('source_connection_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_acl_membership_group', 'access_control_membership', ['organization_id', 'group_id'], unique=False)
    op.create_index('idx_acl_membership_member', 'access_control_membership', ['organization_id', 'member_id', 'member_type'], unique=False)
    op.create_index('idx_acl_membership_source', 'access_control_membership', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_access_control_membership_group_id'), 'access_control_membership', ['group_id'], unique=False)
    op.create_index(op.f('ix_access_control_membership_member_id'), 'access_control_membership', ['member_id'], unique=False)
    op.create_index(op.f('ix_access_control_membership_organization_id'), 'access_control_membership', ['organization_id'], unique=False)
    op.create_index('uq_acl_membership', 'access_control_membership', ['organization_id', 'member_id', 'member_type', 'group_id', 'source_connection_id'], unique=True)
    op.create_table('node_selection',
    sa.Column('source_connection_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.String(length=512), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('node_title', sa.String(length=512), nullable=True),
    sa.Column('node_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_connection_id'], ['source_connection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_node_selection_source_conn', 'node_selection', ['source_connection_id'], unique=False)
    op.create_index(op.f('ix_node_selection_organization_id'), 'node_selection', ['organization_id'], unique=False)
    op.create_index('uq_node_selection_source_node', 'node_selection', ['source_connection_id', 'source_node_id'], unique=True)
    # ### end Alembic commands ###

    # --- Raw SQL objects not captured by autogenerate ---

    op.execute("""
        CREATE OR REPLACE FUNCTION update_entity_count()
        RETURNS TRIGGER AS $$
        BEGIN
            IF TG_OP = 'INSERT' AND NEW.entity_definition_short_name IS NULL THEN
                RETURN NEW;
            END IF;
            IF TG_OP = 'DELETE' AND OLD.entity_definition_short_name IS NULL THEN
                RETURN OLD;
            END IF;
            IF TG_OP = 'UPDATE' AND (
                NEW.entity_definition_short_name IS NULL
                OR OLD.entity_definition_short_name IS NULL
            ) THEN
                RETURN NEW;
            END IF;

            IF TG_OP = 'INSERT' THEN
                INSERT INTO entity_count (
                    sync_id, entity_definition_short_name, count,
                    created_at, modified_at
                )
                VALUES (
                    NEW.sync_id, NEW.entity_definition_short_name, 1,
                    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                )
                ON CONFLICT (sync_id, entity_definition_short_name)
                DO UPDATE SET
                    count = entity_count.count + 1,
                    modified_at = CURRENT_TIMESTAMP;

            ELSIF TG_OP = 'DELETE' THEN
                UPDATE entity_count
                SET count = GREATEST(0, count - 1),
                    modified_at = CURRENT_TIMESTAMP
                WHERE sync_id = OLD.sync_id
                  AND entity_definition_short_name = OLD.entity_definition_short_name;

                DELETE FROM entity_count
                WHERE sync_id = OLD.sync_id
                  AND entity_definition_short_name = OLD.entity_definition_short_name
                  AND count = 0;

            ELSIF TG_OP = 'UPDATE' THEN
                IF OLD.sync_id != NEW.sync_id
                   OR OLD.entity_definition_short_name != NEW.entity_definition_short_name
                THEN
                    UPDATE entity_count
                    SET count = GREATEST(0, count - 1),
                        modified_at = CURRENT_TIMESTAMP
                    WHERE sync_id = OLD.sync_id
                      AND entity_definition_short_name = OLD.entity_definition_short_name;

                    INSERT INTO entity_count (
                        sync_id, entity_definition_short_name, count,
                        created_at, modified_at
                    )
                    VALUES (
                        NEW.sync_id, NEW.entity_definition_short_name, 1,
                        CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
                    )
                    ON CONFLICT (sync_id, entity_definition_short_name)
                    DO UPDATE SET
                        count = entity_count.count + 1,
                        modified_at = CURRENT_TIMESTAMP;
                END IF;
            END IF;

            IF TG_OP = 'DELETE' THEN
                RETURN OLD;
            ELSE
                RETURN NEW;
            END IF;
        END;
        $$ LANGUAGE plpgsql;
    """)

    op.execute("""
        CREATE TRIGGER entity_count_trigger
        AFTER INSERT OR UPDATE OR DELETE ON entity
        FOR EACH ROW
        EXECUTE FUNCTION update_entity_count();
    """)


def downgrade():
    # --- Raw SQL objects ---
    op.execute("DROP TRIGGER IF EXISTS entity_count_trigger ON entity")
    op.execute("DROP FUNCTION IF EXISTS update_entity_count()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_node_selection_source_node', table_name='node_selection')
    op.drop_index(op.f('ix_node_selection_organization_id'), table_name='node_selection')
    op.drop_index('idx_node_selection_source_conn', table_name='node_selection')
    op.drop_table('node_selection')
    op.drop_index('uq_acl_membership', table_name='access_control_membership')
    op.drop_index(op.f('ix_access_control_membership_organization_id'), table_name='access_control_membership')
    op.drop_index(op.f('ix_access_control_membership_member_id'), table_name='access_control_membership')
    op.drop_index(op.f('ix_access_control_membership_group_id'), table_name='access_control_membership')
    op.drop_index('idx_acl_membership_source', table_name='access_control_membership')
    op.drop_index('idx_acl_membership_member', table_name='access_control_membership')
    op.drop_index('idx_acl_membership_group', table_name='access_control_membership')
    op.drop_table('access_control_membership')
    op.drop_index(op.f('ix_source_connection_organization_id'), table_name='source_connection')
    op.drop_index('idx_source_connection_sync_id', table_name='source_connection')
    op.drop_index('idx_source_connection_connection_id', table_name='source_connection')
    op.drop_index('idx_source_connection_collection_id', table_name='source_connection')
    op.drop_table('source_connection')
    op.drop_index('idx_sync_connection_sync_id', table_name='sync_connection')
    op.drop_index('idx_sync_connection_connection_id', table_name='sync_connection')
    op.drop_table('sync_connection')
    op.drop_index('idx_entity_sync_job_id', table_name='entity')
    op.drop_index('idx_entity_sync_id_entity_def_short_name', table_name='entity')
    op.drop_index('idx_entity_sync_id', table_name='entity')
    op.drop_index('idx_entity_entity_id_sync_id', table_name='entity')
    op.drop_index('idx_entity_entity_id', table_name='entity')
    op.drop_index('idx_entity_entity_def_short_name', table_name='entity')
    op.drop_table('entity')
    op.drop_index(op.f('ix_connection_init_session_state'), table_name='connection_init_session')
    op.drop_index(op.f('ix_connection_init_session_organization_id'), table_name='connection_init_session')
    op.drop_index('idx_connection_init_session_expires_at', table_name='connection_init_session')
    op.drop_table('connection_init_session')
    op.drop_index(op.f('ix_usage_organization_id'), table_name='usage')
    op.drop_index('ix_usage_billing_period_id', table_name='usage')
    op.drop_table('usage')
    op.drop_index(op.f('ix_sync_job_organization_id'), table_name='sync_job')
    op.drop_index('idx_sync_job_sync_id', table_name='sync_job')
    op.drop_index('idx_sync_job_status_started_at', table_name='sync_job')
    op.drop_index('idx_sync_job_status_modified_at', table_name='sync_job')
    op.drop_index('idx_sync_job_status', table_name='sync_job')
    op.drop_table('sync_job')
    op.drop_index(op.f('ix_sync_cursor_organization_id'), table_name='sync_cursor')
    op.drop_table('sync_cursor')
    op.drop_index('ix_search_queries_user_created', table_name='search_queries')
    op.drop_index('ix_search_queries_retrieval_strategy', table_name='search_queries')
    op.drop_index('ix_search_queries_results_count', table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_organization_id'), table_name='search_queries')
    op.drop_index('ix_search_queries_org_created', table_name='search_queries')
    op.drop_index('ix_search_queries_is_streaming', table_name='search_queries')
    op.drop_index('ix_search_queries_duration', table_name='search_queries')
    op.drop_index('ix_search_queries_collection_created', table_name='search_queries')
    op.drop_index('ix_search_queries_api_key_created', table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index('idx_entity_count_sync_id', table_name='entity_count')
    op.drop_index('idx_entity_count_entity_def_short_name', table_name='entity_count')
    op.drop_table('entity_count')
    op.drop_index('idx_connection_organization_id', table_name='connection')
    op.drop_index('idx_connection_integration_credential_id', table_name='connection')
    op.drop_table('connection')
    op.drop_table('user_organization')
    op.drop_index(op.f('ix_sync_organization_id'), table_name='sync')
    op.drop_table('sync')
    op.drop_index(op.f('ix_source_rate_limits_organization_id'), table_name='source_rate_limits')
    op.drop_table('source_rate_limits')
    op.drop_index(op.f('ix_redirect_session_organization_id'), table_name='redirect_session')
    op.drop_index(op.f('ix_redirect_session_code'), table_name='redirect_session')
    op.drop_index('idx_redirect_session_expires_at', table_name='redirect_session')
    op.drop_table('redirect_session')
    op.drop_table('organization_billing')
    op.drop_index(op.f('ix_integration_credential_organization_id'), table_name='integration_credential')
    op.drop_table('integration_credential')
    op.drop_index(op.f('ix_feature_flag_organization_id'), table_name='feature_flag')
    op.drop_table('feature_flag')
    op.drop_index('idx_entity_relation_to', table_name='entity_relation')
    op.drop_index('idx_entity_relation_from', table_name='entity_relation')
    op.drop_table('entity_relation')
    op.drop_table('entity_definition')
    op.drop_index(op.f('ix_collection_organization_id'), table_name='collection')
    op.drop_index('idx_collection_vdb_metadata_id', table_name='collection')
    op.drop_table('collection')
    op.drop_index('ix_billing_period_org_status', table_name='billing_period')
    op.drop_index('ix_billing_period_org_dates', table_name='billing_period')
    op.drop_table('billing_period')
    op.drop_table('auth_provider')
    op.drop_index(op.f('ix_api_key_organization_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_table('vector_db_deployment_metadata')
    op.drop_table('user')
    op.drop_index(op.f('ix_processed_webhook_event_stripe_event_id'), table_name='processed_webhook_event')
    op.drop_table('processed_webhook_event')
    op.drop_index('idx_organization_auth0_org_id', table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
