"""Add sync_destination table

Revision ID: 987bcb4abc4d
Revises: 86c0732b1e07
Create Date: 2025-03-10 13:22:50.062013

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = "987bcb4abc4d"
down_revision = "86c0732b1e07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_destination",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("modified_at", sa.DateTime(), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_by_email", sa.String(), nullable=False),
        sa.Column("modified_by_email", sa.String(), nullable=False),
        sa.Column("sync_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("connection_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("is_native", sa.Boolean(), default=False),
        sa.Column("destination_type", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_email"], ["user.email"], name="fk_sync_destination_created_by_email"
        ),
        sa.ForeignKeyConstraint(
            ["modified_by_email"], ["user.email"], name="fk_sync_destination_modified_by_email"
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organization.id"], name="fk_sync_destination_organization_id"
        ),
        sa.ForeignKeyConstraint(
            ["sync_id"], ["sync.id"], ondelete="CASCADE", name="fk_sync_destination_sync_id"
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connection.id"],
            ondelete="CASCADE",
            name="fk_sync_destination_connection_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sync_id", "connection_id", name="uq_sync_connection"),
    )
    op.create_index(
        op.f("ix_sync_destination_sync_id"), "sync_destination", ["sync_id"], unique=False
    )
    op.create_index(
        op.f("ix_sync_destination_connection_id"),
        "sync_destination",
        ["connection_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sync_destination_connection_id"), table_name="sync_destination")
    op.drop_index(op.f("ix_sync_destination_sync_id"), table_name="sync_destination")
    op.drop_table("sync_destination")
    # ### end Alembic commands ###
